/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import com.logic.Client;
import com.logic.DAoCStarter;
import com.logic.TaskManager;
import java.awt.Toolkit;
import java.util.List;
import static com.data.DataClass.*;
/**
 * MADE IN ITALY
 * @author simone
 */
public class FormKill extends javax.swing.JFrame {

	public FormKill() {
		initComponents();
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(ICON)));
	}

	public static void listRefrescher() {
		Object object = jList.getSelectedValue();
		jList.setModel(DAoCStarter.getClientModel());
		jList.setSelectedValue(object, true);
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_kill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jButton_killAll = new javax.swing.JButton();

        setTitle("Kill Clients");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton_kill.setText("Kill");
        jButton_kill.setToolTipText("Kill the selected client(s)");
        jButton_kill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_killActionPerformed(evt);
            }
        });

        jList.setModel(DAoCStarter.getClientModel());
        jList.setToolTipText("List of current running DAoC's clients");
        jScrollPane1.setViewportView(jList);

        jButton_killAll.setText("Kill All");
        jButton_killAll.setToolTipText("Kill all clients!");
        jButton_killAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_killAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton_kill, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_killAll))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_kill, jButton_killAll});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_kill)
                    .addComponent(jButton_killAll)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   private void jButton_killActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_killActionPerformed
      try {
			List<Object> list = jList.getSelectedValuesList();
			for (int i = 0; i < list.size(); i++) {
				if (list.get(i) instanceof Client) {
					Client client = (Client)list.get(i);
					TaskManager.killProcess(client.PID);
				}
			}
			jList.setModel(DAoCStarter.getClientModel());
		}
		catch (Exception e) {
			System.out.println("errore nella gestione del pulsante kill della formkill");
		}
   }//GEN-LAST:event_jButton_killActionPerformed

    private void jButton_killAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_killAllActionPerformed
        while (TaskManager.isProcessRunning(GAME_DLL))
			TaskManager.killProcess(GAME_DLL);
    }//GEN-LAST:event_jButton_killAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButton_kill;
    private static javax.swing.JButton jButton_killAll;
    private static javax.swing.JList jList;
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
